"""initial schema

Revision ID: 3a1974cc55cf
Revises: 
Create Date: 2026-07-18 01:49:34.991293

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3a1974cc55cf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('personal', 'team', name='workspacekind', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('projects',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', name='workspacerole', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_members'))
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_table('account_lists',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'tiktok', 'threads', name='platformslug', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_account_lists_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_lists')),
    sa.UniqueConstraint('project_id', 'platform', name=op.f('uq_account_lists_project_id_platform'))
    )
    op.create_index(op.f('ix_account_lists_project_id'), 'account_lists', ['project_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'scraping', 'summarizing', 'done', 'failed', name='runstatus', native_enum=False, length=20), nullable=False),
    sa.Column('progress_accounts', sa.Integer(), nullable=False),
    sa.Column('progress_items', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_days BETWEEN 1 AND 7', name=op.f('ck_analysis_runs_duration_days_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_analysis_runs_project_id_projects')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_analysis_runs_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('accounts',
    sa.Column('account_list_id', sa.Uuid(), nullable=False),
    sa.Column('input_url', sa.String(length=500), nullable=False),
    sa.Column('normalized_url', sa.String(length=500), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'failed', name='accountstatus', native_enum=False, length=20), nullable=False),
    sa.Column('fail_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_list_id'], ['account_lists.id'], name=op.f('fk_accounts_account_list_id_account_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('account_list_id', 'normalized_url', name=op.f('uq_accounts_account_list_id_normalized_url'))
    )
    op.create_index(op.f('ix_accounts_account_list_id'), 'accounts', ['account_list_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_usage_events_run_id_analysis_runs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index(op.f('ix_usage_events_run_id'), 'usage_events', ['run_id'], unique=False)
    op.create_index('ix_usage_events_user_created', 'usage_events', ['user_id', 'created_at'], unique=False)
    op.create_table('content_items',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('reel', 'post', 'carousel', 'video', 'short', name='contenttype', native_enum=False, length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_content_items_account_id_accounts')),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_content_items_run_id_analysis_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items'))
    )
    op.create_index(op.f('ix_content_items_account_id'), 'content_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_content_items_run_id'), 'content_items', ['run_id'], unique=False)
    op.create_table('shortlist_items',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_shortlist_items_added_by_users')),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_shortlist_items_content_item_id_content_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_shortlist_items_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortlist_items'))
    )
    op.create_index(op.f('ix_shortlist_items_project_id'), 'shortlist_items', ['project_id'], unique=False)
    op.create_index('uq_shortlist_items_active', 'shortlist_items', ['project_id', 'content_item_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    # ### end Alembic commands ###

    # DB-side safeguard for the 50-accounts-per-list product cap (D13).
    # Primary enforcement is app-level (E2-S2); this trigger is the backstop.
    op.execute(
        """
        CREATE FUNCTION enforce_account_list_cap() RETURNS trigger AS $$
        BEGIN
            IF (SELECT count(*) FROM accounts WHERE account_list_id = NEW.account_list_id) >= 50
            THEN
                RAISE EXCEPTION 'account list % already has 50 accounts', NEW.account_list_id
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER account_list_cap
        BEFORE INSERT ON accounts
        FOR EACH ROW EXECUTE FUNCTION enforce_account_list_cap()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER account_list_cap ON accounts")
    op.execute("DROP FUNCTION enforce_account_list_cap()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_shortlist_items_active', table_name='shortlist_items', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_shortlist_items_project_id'), table_name='shortlist_items')
    op.drop_table('shortlist_items')
    op.drop_index(op.f('ix_content_items_run_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_account_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index('ix_usage_events_user_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_run_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_accounts_account_list_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_account_lists_project_id'), table_name='account_lists')
    op.drop_table('account_lists')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
